name: Build and Publish image to DockerHub
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  # debug:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dump env
  #       run: env | sort
  #     - name: DEBUG
  #       env:
  #         GITHUB_CONTEXT: ${{ toJson(github) }}
  #       run: echo "$GITHUB_CONTEXT"

  publish_images:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Don't use project name since it has the '-container'.  Dockerhub JLab
          # namespace is annoyingly different that GitHub's so we can't use that.
          images: jeffersonlab/rfscopedb
          tags: type=semver,pattern={{version}}
      - 
        name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and Push
        uses: docker/build-push-action@v6
        with:
          build-args: CUSTOM_CRT_URL=http://pki.jlab.org/JLabCA.crt
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
                
